services:
  frontend:
    image: edit-man-frontend
    build: ./edit-man
    volumes:
      - ./edit-man:/app
      - /app/node_modules
    ports:
      - 5173:5173
  backend:
    image: edit-man-backend
    build: ./edit-man-api
    volumes:
      - ./edit-man-api/src:/app
    ports:
      - 8000:8000